name: mac flow

on:
  workflow_dispatch:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

jobs:
  build:

    runs-on: macos-12
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Prep selenium folder
        run: |
          if [ ! -d "/usr/local/opt/selenium4" ]; then mkdir /usr/local/opt/selenium4; fi
          if [ ! -f "/opt/selenium4/selenium-server-4.4.0.jar" ]; then
            wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.4.0/selenium-server-4.4.0.jar -P /usr/local/opt/selenium4
          fi
          ls -ltr /usr/local/opt/selenium4
      - name: Setup JAVA HOME 
        run: |
          sudo apt update
          #yes | sudo apt install maven
          chrome --version
          git --version
          java --version
          #export JAVA_HOME=/usr/local/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.16-101/x64
          printenv
